// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "client.h"

std::string client::echo(const std::string& text)
{
    return "Hi, " + text;
}

